name: Deploy to EC2 and Invalidate CloudFront

on:
  push:
    branches:
      - main # Trigger otomatis setiap kali kamu push ke branch main

jobs:
  deploy:
    # Menggunakan label sesuai dengan runner ARM64 (Graviton) yang kamu miliki
    runs-on: [self-hosted, linux, arm64]

    steps:
      # 1. Mengambil kode terbaru dari repository GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Menginstal library Node.js (node_modules)
      - name: Install dependencies
        run: npm install

      # 3. Melakukan build React/Vite (menghasilkan folder dist)
      - name: Build project
        run: npm run build

      # 4. Memindahkan isi folder dist ke folder Apache (/var/www/html)
      # Pastikan kamu sudah menjalankan: echo "ec2-user ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/github-runner
      - name: Deploy to Apache folder
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r dist/* /var/www/html/
          sudo systemctl restart httpd

      # 5. Otomatis membersihkan Cache CloudFront (Invalidation)
      # GANTI [ID_DISTRIBUSI_KAMU] dengan ID dari dashboard CloudFront (contoh: E1234567ABCDEFG)
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E3E19GIS918SK --paths "/*"